### ISSUE TITLE
When data transfer fails, log more information to assist troubleshooting

### ISSUE THREAD

**Issue by jesusbagpuss** [eprintsug/irus#4]
The recent change from http to https for the IRUS-UK end point has revealed that some errors (e.g. when the `$ua->head` is not successful) are hidden/difficult to debug.

Possible improvements:
* when creating a `replay` event, add the '_msg' from the $ua response to the event description
* when creating a `replay` event, print details from the $ua response to STDERR (apache error log)
* when running a `replay` event, print details from the $ua response to STDERR (indexer.log)

**Comment by Ainmhidh** [comment]
I think all three options together is pretty reasonable?  That way anyone checking any of those would see the error details and know to check further.

**Comment by jesusbagpuss** [comment]
Calling `$r->message` returns the human-readable form of the HTTP response code e.g. `Not found`.

Calling `$r->as_string` (when the request was not successful) output some slightly more technical information (http headers etc.), but I think these are more useful for debugging e.g.
```
HTTP/1.1 404 Not Found
Cache-Control: max-age=604800
Date: Tue, 15 Oct 2019 12:52:50 GMT
Server: EOS (vny006/0450)
Vary: Accept-Encoding
Content-Length: 1270
Content-Type: text/html; charset=UTF-8
Expires: Tue, 22 Oct 2019 12:52:50 GMT
Client-Date: Tue, 15 Oct 2019 12:51:38 GMT
Client-Peer: 93.184.216.34:443
Client-Response-Num: 1
Client-SSL-Cert-Issuer: /C=US/O=DigiCert Inc/CN=DigiCert SHA2 Secure Server CA
Client-SSL-Cert-Subject: /C=US/ST=California/L=Los Angeles/O=Internet Corporation for Assigned Names and Numbers/OU=Technology/CN=www.example.org
Client-SSL-Cipher: ECDHE-RSA-AES128-GCM-SHA256
Client-SSL-Socket-Class: IO::Socket::SSL
```
or
```
500 Can't connect to a.b.c.d.e.f.g:443
Content-Type: text/plain
Client-Date: Tue, 15 Oct 2019 12:53:55 GMT
Client-Warning: Internal response

Can't connect to a.b.c.d.e.f.g:443

Name or service not known at /usr/share/perl5/LWP/Protocol/http.pm line 51.
```

The description field for an event is a longtext field - so can store a sensible amount of info.

**Comment by Ainmhidh** [comment]
Thinking the following for cfg.d/pirus.pl
108.5		$event->set_value( "description", $r->as_string );
108.6 print STDERR $r->as_string;

Not had chance to test it yet though.

**Comment by jesusbagpuss** [comment]
> Not had chance to test it yet though.

I have (before making the above suggestion :o)
There's a couple of other changes - I'll make a PR this afternoon for a v.1.2.2.
